### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by silviyaboteva** [telerik/react-coffee-warehouse#2]
Here we will list the todos for the demo.

## Header
 - [x] Setup localization via DropDownList.
 - [x] Change the profile picture upon uploading new from the profile page.
 - [x] Responsive styles

## Dashboard page
 - [x] Selecting "My Team" button => setup filtering of the Grid by team that the user is into (check Profile page's radiogroup selection).
 - [x] Setup DateRangePicker to filer the Chart.
 - [x] Responsive styles

## Planning page
- [x] Add Card components
- [x] Add Scheduler component
 - [x] Responsive styles

## Profile page
 - [x] Add Switch component
 - [x] Add RadioGroup component
 - [x] Responsive styles

## Info page
- [x] Add all used components to the grid at the end.
 - [x] Responsive styles
